# This is default and very simple configuration file for Yasb. 
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: false
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
        "home",
        "active_window"
      ]
      center: [
        glazewm_workspaces
      ]
      right: [
        "glazewm_tiling_direction", 
        "wifi",
        "microphone",
        "volume",
        "battery", 
        "clock"
        ]
widgets:

  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
  
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>  </span>"
      menu_list:
      - { title: "AlfredLaptop", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
      - { title: "Documents", path: "~\\Documents" }
      - { title: "Pictures", path: "~\\Pictures" }
    system_menu: true
    power_menu: true
    blur: false
  
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 18
      max_length: 32
      max_length_ellipsis: "..."
      monitor_exclusive: true
  
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d %b %H:%M}"
      label_alt: "{%A %d %B %Y %H:%M}"
      timezones: []
      callbacks:
        on_left: "toggle_label"
  
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{volume}"
      volume_icons:
        - "󰖁 "  # Volume Mute
        - "󰕿 "  # Volume Basso
        - "󰖀 "  # Volume Medio
        - "󰕾 "  # Volume Alto
      callbacks:
        on_left: "toggle_mute"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "time remaining: {time_remaining}"
      update_interval: 5000  
      time_remaining_natural: true
      charging_options:
        icon_format: "{icon}"
        blink_charging_icon: true
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "󰂄"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\uf240"
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      animation:
        enabled: true
        type: "fadeInOut"
        duration: 200
  
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span>"
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "do_nothing"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  
  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "<span>{wifi_icon}</span>"
        label_alt: "<span>{wifi_icon}</span> {wifi_name}"
        update_interval: 5000
        wifi_icons:
          - " 󰖪 " # 0% strength (no wifi)
          - " 󰤟 " # 1-25% strength
          - " 󰤢 " # 26-50% strength
          - " 󰤥 " # 51-75% strength
          - " 󰖩 " # 76-100% strength. Alternate theming: \uf1eb
        callbacks:
          on_left: "exec quick_settings"
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"
    
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
  # power_menu:
  #   type: "yasb.power_menu.PowerMenuWidget"
  #   options:
  #     label: "\uf011"
  #     uptime: True
  #     blur: False
  #     blur_background: True
  #     animation_duration: 200
  #     button_row: 5
  #     buttons:
  #       shutdown: ["\uf011", "Shut Down"]
  #       restart: ["\uead2", "Restart"]
  #       signout: ["\udb80\udf43", "Sign out"]
  #       hibernate: ["\uf28e", "Hibernate"]
  #       sleep: ["\u23fe", "Sleep"]
  #       cancel: ["", "Cancel"]
  # apps:
  #   type: "yasb.applications.ApplicationsWidget"
  #   options:
  #     container_padding:
  #       top: 0
  #       left: 8
  #       bottom: 0
  #       right: 8
  #     label: "{data}"
  #     app_list:
  #       - { icon: "\uf422", launch: "search" }
  #       - { icon: "\ueb03", launch: "cmd /c Taskmgr" }
  #       - { icon: "\udb80\ude39",launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" }
  # taskbar:
  #   type: "yasb.taskbar.TaskbarWidget"
  #   options:
  #     animation:
  #       enabled: true
  #     icon_size: 16
  #     ignore_apps:
  #       processes: []
  #       titles: []
  #       classes: []
  #     container_padding:
  #       top: 0
  #       left: 0
  #       bottom: 0
  #       right: 0
  # weather:
  #   type: "yasb.weather.WeatherWidget"
  #   options:
  #     label: "<span>{icon}</span> {temp}"
  #     label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
  #     api_key: "3bf4cf9a7c3f40d6b31174128242807"
  #     update_interval: 600
  #     hide_decimal: true
  #     location: "USA Los Angeles 90006"
  #     callbacks:
  #       on_left: "toggle_label"
  #     icons:
  #       sunnyDay: "\udb81\udd99"
  #       clearNight: "\udb81\udd99"
  #       cloudyDay: "\udb81\udd99"
  #       cloudyNight: "\udb81\udd99"
  #       rainyDay: "\udb81\udd99"
  #       rainyNight: "\udb81\udd99"
  #       snowyIcyDay: "\udb81\udd99"
  #       snowyIcyNight: "\udb81\udd99"
  #       blizzard: "\udb81\udd99"
  #       default: "\udb81\udd99"


   # media:
  #   type: "yasb.media.MediaWidget"
  #   options:
  #     label: "{title}"
  #     label_alt: "{artist}"
  #     max_field_size:
  #       label: 64
  #       label_alt: 24
  #     show_thumbnail: true
  #     controls_only: false
  #     controls_left: true
  #     hide_empty: true
  #     thumbnail_alpha: 150
  #     thumbnail_padding: 8
  #     thumbnail_corner_radius: 0
  #     icons:
  #       prev_track: "\ue892"
  #       next_track: "\ue893"
  #       play: "\ue768"
  #       pause: "\ue769"